before_install:
  - gem install bundler
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
    - jdk:
      - oraclejdk8
      - oraclejdk7
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - ruby-head
  - jruby-9.1.7.0

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

script: bundle exec rspec
