sudo: false
language: ruby
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - 2.5.7
  - 2.6.0
  - ruby-head
  - jruby-9.1.9.0
  - jruby-head
before_install:
  - gem install bundler
  - gem update bundler
script: bundle exec rspec

