before_install:
  - gem update bundler
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
  include:
    - gemfile: Gemfile
      rvm: 2.0.0
      env: COVERAGE=1
rvm:
  - 2.2.3
  - ruby-head
  - jruby-9.1.7.0

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

script: bundle exec rspec
